<?php

/**
 * Implementation of hook_menu().
 */
function oauth_common_consumerui_menu() {
  $menu = array();
  $only_consumer = !module_exists('oauth_common_providerui');

  $admin_base = array(
    'access arguments' => array('administer oauth'),
    'file' => 'oauth_common_consumerui.inc',
  );

  $menu['admin/settings/oauth/consumers'] = array(
    'title' => 'Consumers',
    'description' => 'Consumers that are used to access external services',
    'page callback' => 'oauth_common_consumerui_list_consumers',
    'type' => MENU_LOCAL_TASK,
    'weight' => 10,
  ) + $admin_base;

  if ($only_consumer) {
    $menu['user/%user/oauth'] = array(
      'title' => 'Access',
      'page callback' => 'oauth_common_page_user_authorizations',
      'page arguments' => array(1, FALSE),
      'access callback' => '_oauth_common_user_access',
      'access arguments' => array(1),
      'file' => 'oauth_common.authorizations.inc',
      'type' => MENU_LOCAL_TASK,
    );
  }

  $menu['user/%user/oauth/access'] = array(
    'title' => 'Access tokens',
    'page callback' => 'oauth_common_page_user_authorizations',
    'page arguments' => array(1, FALSE),
    'access callback' => '_oauth_common_user_access',
    'access arguments' => array(1),
    'file' => 'oauth_common.authorizations.inc',
    'type' => $only_consumer ? MENU_DEFAULT_LOCAL_TASK : MENU_LOCAL_TASK,
  );

  $menu['user/%user/oauth/access/%oauth_common_consumer_token'] = array(
    'title' => 'Edit access token',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('oauth_common_form_authorization', 4),
    'access callback' => '_oauth_common_user_access',
    'access arguments' => array(1, 'oauth authorize consumers'),
    'file' => 'oauth_common.authorizations.inc',
    'type' => MENU_LOCAL_TASK,
  );

  $menu['user/%user/oauth/access/%oauth_common_consumer_token/ahah/secret'] = array(
    'page callback' => 'oauth_common_ahah_secret',
    'page arguments' => array(4),
    'access callback' => '_oauth_common_user_access',
    'access arguments' => array(1, 'oauth authorize consumers'),
    'file' => 'oauth_common.inc',
    'type' => MENU_CALLBACK,
  );

  $menu['user/%user/oauth/access/%oauth_common_consumer_token/delete'] = array(
    'title' => 'Delete access token',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('oauth_common_form_authorization_delete', 1, 4),
    // We always want to allow the user to delete a authorization, that
    // shouldn't be a permission that can be rescinded.
    'access callback' => 'user_edit_access',
    'access arguments' => array(1),
    'file' => 'oauth_common.authorizations.inc',
    'type' => MENU_LOCAL_TASK,
  );

  return $menu;
}
